name: CI

on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get install meson ninja-build libglfw3 libglfw3-dev libglew2.1 libglew-dev
    - run: meson setup build --debug -Db_sanitize=address,undefined
      env:
        CC: gcc
    - run: meson test -C build --verbose
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
